crab submit -c crab_QCDbcToE1.py
crab submit -c crab_QCDbcToE2.py
crab submit -c crab_QCDbcToE3.py
crab submit -c crab_QCDbcToE4.py
crab submit -c crab_QCDbcToE5.py
crab submit -c crab_QCDbcToE6.py
crab submit -c crab_QCDem1.py
crab submit -c crab_QCDem2.py
crab submit -c crab_QCDem3.py
crab submit -c crab_QCDem4.py
crab submit -c crab_QCDem5.py
crab submit -c crab_QCDem6.py
crab submit -c crab_QCDem7.py
crab submit -c crab_QCDem8.py
crab submit -c crab_QCDmu1.py
crab submit -c crab_QCDmu10.py
crab submit -c crab_QCDmu11.py
crab submit -c crab_QCDmu12.py
crab submit -c crab_QCDmu2.py
crab submit -c crab_QCDmu3.py
crab submit -c crab_QCDmu4.py
crab submit -c crab_QCDmu5.py
crab submit -c crab_QCDmu6.py
crab submit -c crab_QCDmu7.py
crab submit -c crab_QCDmu8.py
crab submit -c crab_QCDmu9.py
crab submit -c crab_WW.py
crab submit -c crab_ZZ.py

crab submit -c crab_ttH.py
crab submit -c crab_ttWhad.py
crab submit -c crab_ttWlep.py
